In [1]:
import numpy as np

In [183]:
data = np.arange(1,101).reshape(10,10)
print data

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [184]:
target_row = 7
target_col = 6
print annulizer(data, target_row, target_col)

[77]
[66, 67, 68, 76, 78, 86, 87, 88]
[55, 56, 57, 58, 59, 65, 69, 75, 79, 85, 89, 95, 96, 97, 98, 99]
[44, 45, 46, 47, 48, 49, 50, 54, 60, 64, 70, 74, 80, 84, 90, 94, 100]
[33, 34, 35, 36, 37, 38, 39, 40, 43, 53, 63, 73, 83, 93]
[22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 42, 52, 62, 72, 82, 92]
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 31, 41, 51, 61, 71, 81, 91]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[77.0, 77.0, 77.0, 64.647058823529406, 50.0, 41.75, 33.5, 5.5]
[[ 5  5  5  5  5  5  5  5  5  5]
 [33 33 33 33 33 33 33 33 33 33]
 [33 41 41 41 41 41 41 41 41 41]
 [33 41 50 50 50 50 50 50 50 50]
 [33 41 50 64 64 64 64 64 64 64]
 [33 41 50 64 77 77 77 77 77 64]
 [33 41 50 64 77 77 77 77 77 64]
 [33 41 50 64 77 77 77 77 77 64]
 [33 41 50 64 77 77 77 77 77 64]
 [33 41 50 64 77 77 77 77 77 64]]


In [182]:
def annulizer(data, target_row, target_col):
    hive = []
    for step in range(max(data.shape[0]-target_row,
                          data.shape[1]-target_col,
                          data.shape[0]-2,
                          data.shape[1]-2)):
        ring = []
        for i in range(-step,step+1):
            if i == -step or i == step:
                for j in range(-step,step+1):
                    if target_row+i >= 0 and target_col+j >= 0:
                        try:
                            ring.append(data[target_row+i][target_col+j])
                        except IndexError:
                            pass
            else:
                for j in (-step, step):
                    if target_row+i >= 0 and target_col+j >= 0:
                        try:
                            ring.append(data[target_row+i][target_col+j])
                        except IndexError:
                            pass
        hive.append(np.mean(ring))
        print ring
    print hive
    for step in range(max(data.shape[0]-target_row,
                          data.shape[1]-target_col,
                          data.shape[0]-2,
                          data.shape[1]-2)):
        for i in range(-step,step+1):
            if i == -step or i == step:
                for j in range(-step,step+1):
                    if target_row+i >= 0 and target_col+j >= 0:
                        try:
                            data[target_row+i][target_col+j] = hive[step]
                        except IndexError:
                            pass
            else:
                for j in (-step, step):
                    if target_row+i >= 0 and target_col+j >= 0:
                        try:
                            data[target_row+i][target_col+j] = hive[step]
                        except IndexError:
                            pass
    return data